# Generated by Django 2.2.1 on 2022-06-17 21:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20220616_0036'),
        ('Agent', '0002_auto_20220616_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_store',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='Company.Agent'),
        ),
    ]
