# Generated by Django 2.2.1 on 2022-06-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_auto_20220617_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_to_store',
            new_name='add_to_store_agent',
        ),
    ]
