# Generated by Django 4.1.3 on 2022-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0007_auto_20220617_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='Adis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='new',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='newBrand',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='newsds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_amount_in_store_agent',
            name='Adis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_amount_in_store_agent',
            name='new',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_amount_in_store_agent',
            name='newBrand',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_amount_in_store_agent',
            name='newsds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
