# Generated by Django 2.2.18 on 2022-06-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_pic',
            field=models.ImageField(blank=True, default='File/Profile/default.png', null=True, upload_to='Profile/'),
        ),
    ]
