# Generated by Django 4.1.3 on 2022-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20220616_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Adis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='new',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='newBrand',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='newsds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='coverArea',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
